### ISSUE TITLE
インプレッションのコンポーネントを削除できていない

### ISSUE THREAD

**Issue by uramnoil** [uramnoil/twitter-hide-impression#2]
## 問題

リツイート・引用リツイート・いいねの表示が右に偏っている。

## 原因

- インプレッションの中のaタグのみを削除している
  * インプレッションのコンポーネント自体を消すことができていない
  * 一意な識別子がそれぞれのコンポーネントに付与されておらず、クエリセレクタでのインプレッションコンポーネントの特定が困難

**Comment by uramnoil** [comment]
https://github.com/uramnoil/twitter-hide-impression/blob/25b58bdd149acd5f1600a1a0cc4cc4ecdc3953eb/src/contentScript.js#L5

**Comment by InkoHX** [comment]
子孫要素が取得できているのであれば、`parentNode`を`remove`してしまえばいいのではないでしょうか？

**Comment by InkoHX** [comment]
```js
analyticses.forEach(analytics => analytics.parentNode.remove())
```
といった感じにすると上手くと思われる。

**Comment by uramnoil** [comment]
確認してきます！
